kafka:
  bootstrap_servers: "127.0.0.1:9092"
  group_id: "go-group"
  auto_offset_reset: "earliest"
consumer_topic_info:
  topic_bom_bartender_printer: "local.bom-product-bartender"
bartender_printer_api:
  is_call_api: false
  method: "POST"
  url: "http://127.0.0.1:5159/api/actions"
  username: "hahahaha"
  password: "hahahaha"
bartender_tracking_status:
  is_call_api: false
  method: "GET"
  url: "http://127.0.0.1:5159/api/actions"
  username: "hahahaha"
  password: "hahahaha"
file_share_path: "/home/nhanlt/Documents/maverick_2025/bartender/data" # For linux, use forward slashes
