kafka:
  bootstrap_servers: "127.0.0.1:9093"
  group_id: "go-group"
  auto_offset_reset: "earliest"
consumer_topic_info:
  topic_bom_bartender_printer: "local.bom-product-bartender-v2"
bartender_printer_api:
  is_call_api: false
  method: "POST"
  url: "http://127.0.0.1:5159/api/actions"
  username: "hahahaha"
  password: "hahahaha"
file_share_path: "\\\\113.161.49.29\\test" 